In [13]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import torch

import pickle as pk

In [14]:
data = pd.read_csv("./data/DataSetTrussStructure.csv")

In [15]:
data

CS1       CS2       CS3       CS4       CS5       CS6   Energie  \
0     0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.025088   
1     0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.043002   
2     0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.021369   
3     0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.044654   
4     0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.036768   
...        ...       ...       ...       ...       ...       ...       ...   
1996  0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.021233   
1997  0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.023403   
1998  0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.020354   
1999  0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.044875   
2000  0.022575  0.022575  0.022575  0.022575  0.022575  0.022575  0.038393   

            Poids  N° image  
0     3901.671856         1  
1     3159.119087         2  
2     3575.895111         3  
3     3276.268680         4  
4     3173.978488         5  
...           ...       ...  
1996  3352.060281      1997  
1997  3338.811195      1998  
1998  3456.720204      1999  
1999  3182.877027      2000  
2000  3197.261485      2001  

[2001 rows x 9 columns]

In [16]:
target_df = data.loc[:, ["Energie", "Poids"]]

In [17]:
target_df

Energie        Poids
0     0.025088  3901.671856
1     0.043002  3159.119087
2     0.021369  3575.895111
3     0.044654  3276.268680
4     0.036768  3173.978488
...        ...          ...
1996  0.021233  3352.060281
1997  0.023403  3338.811195
1998  0.020354  3456.720204
1999  0.044875  3182.877027
2000  0.038393  3197.261485

[2001 rows x 2 columns]

In [20]:
scaler = MinMaxScaler()

In [21]:
scaled_target = scaler.fit_transform(target_df)

In [32]:
scaled_target

array([[0.20296963, 1.        ],
       [0.92072539, 0.12321718],
       [0.0539329 , 0.61533312],
       ...,
       [0.0132932 , 0.47461516],
       [0.9957525 , 0.1512698 ],
       [0.73604534, 0.16825451]])

In [27]:
scaler.inverse_transform(np.array([[0.3, 0.234]])).tolist()

[[0.02750992197624554, 3252.9417417847512]]

In [30]:
scaler

MinMaxScaler()

In [37]:
pk.dump(scaler, open("min_max_scaler.pkl", "wb"))

In [38]:
scaled_target

array([[0.20296963, 1.        ],
       [0.92072539, 0.12321718],
       [0.0539329 , 0.61533312],
       ...,
       [0.0132932 , 0.47461516],
       [0.9957525 , 0.1512698 ],
       [0.73604534, 0.16825451]])

In [39]:
target = torch.from_numpy(scaled_target)

In [40]:
target

tensor([[0.2030, 1.0000],
        [0.9207, 0.1232],
        [0.0539, 0.6153],
        ...,
        [0.0133, 0.4746],
        [0.9958, 0.1513],
        [0.7360, 0.1683]], dtype=torch.float64)

In [42]:
torch.save(target, "./target_energy_weight.pt")

In [47]:
data = pd.read_csv("./data/DataSetTrussStructureDeplacements.csv").iloc[:, :-1]

In [48]:
data

DX1  DY1       DX2       DY2           DX3           DY3  DX4  DY4
0       0    0 -0.000007 -0.000025  5.195944e-06 -1.989229e-05    0    0
1       0    0 -0.000009 -0.000043 -1.855864e-06 -3.920309e-08    0    0
2       0    0 -0.000006 -0.000021  1.822227e-06 -1.575411e-05    0    0
3       0    0 -0.000012 -0.000045  2.828932e-05  1.415966e-06    0    0
4       0    0 -0.000014 -0.000037  3.128445e-06 -5.127493e-06    0    0
...   ...  ...       ...       ...           ...           ...  ...  ...
1996    0    0 -0.000008 -0.000021  2.114104e-06 -8.535411e-06    0    0
1997    0    0 -0.000009 -0.000023  1.400329e-06 -6.005413e-06    0    0
1998    0    0 -0.000007 -0.000020  1.595819e-06 -1.374284e-05    0    0
1999    0    0 -0.000012 -0.000045  4.560391e-07 -2.466710e-07    0    0
2000    0    0 -0.000012 -0.000038  1.371463e-05  2.062576e-06    0    0

[2001 rows x 8 columns]

In [49]:
scaler_dep = StandardScaler()

In [50]:
data_dep = scaler_dep.fit_transform(data)

In [53]:
data_tensor = torch.from_numpy(data_dep)

In [77]:
list_empty = []

In [78]:
for t in data_tensor:
    list_empty.append([t[:2].tolist(), t[2:4].tolist(), t[4:6].tolist(), t[6:].tolist()])

In [79]:
data_to_save = torch.tensor(list_empty)

In [81]:
data_to_save.shape

torch.Size([2001, 4, 2])